apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pratik50/I.R.I.S.
    targetRevision: HEAD
    path: examples
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
